### ISSUE TITLE
I  cannot find "@Html.Pager(Model)" in my code

### ISSUE THREAD

**Issue by richardsun-voyager** [Webdiyer/MvcPager#5]
I tried to add "@Html.Pager(Model).Options(o => o.SetPageIndexParameterName("id").SetPagerItemTemplate("{0}&nbsp;"))" in the end of my code, but the project did not  could not find Html.Pager, will you please help me? I had imported "using Webdiyer.WebControls.Mvc;" in my controller.

**Comment by Webdiyer** [comment]
You need to add @using Webdiyer.WebControls.Mvc in your View file.

**Comment by richardsun-voyager** [comment]
Thanks very much, Mr. Tao! I got it!
