### ISSUE TITLE
请支持.net core

### ISSUE THREAD

**Issue by wlclass** [Webdiyer/MvcPager#6]
一直在用MvcPager库,非常感谢作者,请推出支持.net core版本

**Comment by Webdiyer** [comment]
在这里：[https://github.com/Webdiyer/MvcPagerCore](https://github.com/Webdiyer/MvcPagerCore)

**Comment by wlclass** [comment]
谢谢,已经找到了,并使用上了, 您没有计划发布.net core 版本的nuget包吗?

**Comment by Webdiyer** [comment]
还不太完善，准备有空再完善一下再发布，因为工作中还没用到.net core，所以开发这个控件就是边学边做，还有不少需要改进的地方。谢谢！
