### ISSUE TITLE
Html: <div data-invalidpageerrmsg="页索引无效" data-outrangeerrmsg="页索引超出范围" data-pagecount="1" data-pageparameter="pageIndex" data-pagerid="Webdiyer.MvcPager" data-urlformat="/News/List?pageIndex=__pageIndex__"></div>

### ISSUE THREAD

**Issue by QianYS** [Webdiyer/MvcPager#8]
Html:
<div data-invalidpageerrmsg="页索引无效" data-outrangeerrmsg="页索引超出范围" data-pagecount="1" data-pageparameter="pageIndex" data-pagerid="Webdiyer.MvcPager" data-urlformat="/News/List?pageIndex=__pageIndex__"></div>

cshtml:
@Html.Pager(Model, new PagerOptions { PageIndexParameterName = "pageIndex" })

controller:
/// 新闻列表
        /// </summary>
        /// <returns></returns>
        public ActionResult List(int pageIndex = 1)
        {
            NewsMainTBService service = new NewsMainTBService();
            var list = service.GetList().ToPagedList(pageIndex, 20) ;
            return View(list);
        }

NewsMainTBService:
public List<NewsMainTB> GetList()
        {
            return _repository.GetList("where DeleteFlag=0 order by IsTop desc, AddTime desc").ToList();
        }

can tell me why html is error?

**Comment by Webdiyer** [comment]
您好，没明白您的意思，错误在哪里？Where's the error?

**Comment by QianYS** [comment]
我引用您的webdiyer  页码无法显示  查看html中显示的是<div data-invalidpageerrmsg="页索引无效" data-outrangeerrmsg="页索引超出范围" data-pagecount="1" data-pageparameter="pageIndex" data-pagerid="Webdiyer.MvcPager" data-urlformat="/News/List?pageIndex=__pageIndex__">  这个
返回值也看过 是有页数的

**Comment by QianYS** [comment]
html 中显示 data-invalidpageerrmsg="页索引无效" data-outrangeerrmsg="页索引超出范围"

**Comment by Webdiyer** [comment]
那是客户端页索引文本框输入验证时要用到的错误消息，本身不是错误！
